### ISSUE TITLE
4.0 release

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge#1319]
The objective of 4.0 is to fix important current bugs, decouple non-core functionality to kproject, ensure testing that detect regressions we had and ensure source-level public API stability for rendering (stabilise uniform buffers) and math (use immutable data classes so when MFVC classes are ready the API is there; this might lead to performance regressions until that happen, but will increase compatibility from day 1 without having to migrate kproject later)

* [x] Fix current bugs
  * [x] Rewrite event & component system
* [x] Decouple non-core functionality to kproject
* [x] Ensure testing that detect graphical regressions (screenshot testing and e2e tests)
* [x] Future-proof rendering - https://github.com/korlibs/korge/pull/1175
* [x] Unmix uniforms & texture units https://github.com/korlibs/korge/issues/1400
* [x] Math compatible with MFVC - https://github.com/korlibs/korge/issues/1257
* [x] Remove deprecated APIs
* [x] Rename packages

**Comment by soywiz** [comment]
If WASM is going to be available soon ™, should we start using floats for Point, Matrix, etc.?

**Comment by soywiz** [comment]
So in the end regarding MFVC:

* Removed `IPoint`
* Renamed `Point` -> `MPoint`
* Keeping `MPoint` as `Double`
* Created immutable version of `Point`, using two `Float`s. Wrapping `Long` in JVM/K/N and a custom class in JS (since JS engines are updated and have advanced escape anallisys), and since WASM will be available not too far away
* Done the same for `Size`, `Scale`, `Anchor`
* Created a HalfFloat and Short version for packing 4 values
* Used Half4Pack in `RectCorners` since the values are usually small, but still floating point
* For `Matrix` and other classes required MFVC, mark them as an annotation with a warning to know it allocates

This will be available since `alpha-4`

**Comment by soywiz** [comment]
Proposal of package renames:

Proposal for package renames:
* `klock` -> `korlibs.time`
* `korinject` -> `korlibs.inject`
* `kds` -> `korlibs.ds`
* `kmem` -> `korlibs.mem`
* `korte` -> `korlibs.template`
* `kbignum` -> `korlibs.bignum`
* `krypto` -> `korlibs.crypto`
* `ktruth` -> `korlibs.test`
* `korio` -> `korlibs.io`
* `korma` -> `korlibs.math`
* `korim` -> `korlibs.image`
* `korau` -> `korlibs.audio`
* `korgw` -> `korlibs.gamewindow`
* `korge` -> `korlibs.korge`

**Comment by soywiz** [comment]
When using uniform buffers, we should generate something like this in the shader:

```
#version 300 es

layout(std140, binding = 2) uniform u_testBlock
{
    mediump vec4 v0;
    mediump vec4 v1;
};
```

By using 300 es, we should use `in`, `out` etc. instead of the old syntax. We should be sure that the generated layout matches std140 spec: https://www.oreilly.com/library/view/opengl-programming-guide/9780132748445/app09lev1sec2.html

![app09tab01](https://user-images.githubusercontent.com/570848/224981850-8d0d115e-3484-4b19-8ca2-9e25a86bd896.jpg)

**Comment by soywiz** [comment]
I have merged the separation of samplers, and changed all the code to use uniform blocks.
So now we have: attributes, varyings, uniforms inside uniform blocks and samplers.

**Comment by soywiz** [comment]
Even if it can improve a lot yet. I believe we are in a good shape already to be future-proof. All geometry is already immutable (though not using value classes yet since they are not available), and the AG API is decent enough for typical scenarios to be fast enough.

I'm going to fix bugs, mouse/touch events work as expected, and ensure the code-base use immutable geometry everywhere. And let's start the Beta & RC. And update all kprojects to the new versions + publish the store + update the intellij plugin.

**Comment by soywiz** [comment]
`4.0.0-beta` published. Now API is almost final. I'm going to update all kprojects, fix/add small pending stuff, and go for RC & release in the coming ~2 weeks.
